# Generated by Django 4.2.7 on 2025-07-16 13:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('competitions', '0003_competition_year'),
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='奖项名称')),
                ('description', models.TextField(blank=True, verbose_name='奖项描述')),
                ('level', models.CharField(blank=True, max_length=20, verbose_name='级别')),
                ('prize_money', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='奖金')),
                ('prize_description', models.TextField(blank=True, verbose_name='奖品描述')),
                ('winner_count', models.IntegerField(default=0, verbose_name='获奖者数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='competitions.competition', verbose_name='所属比赛')),
            ],
            options={
                'verbose_name': '奖项',
                'verbose_name_plural': '奖项',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AwardRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='获奖年份')),
                ('description', models.TextField(blank=True, verbose_name='获奖描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='awards.award', verbose_name='奖项')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_records', to='groups.group', verbose_name='获奖社团')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_records', to='videos.video', verbose_name='获奖视频')),
            ],
            options={
                'verbose_name': '获奖记录',
                'verbose_name_plural': '获奖记录',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
