# Generated by Django 4.2.7 on 2025-07-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardrecord",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_records",
                to="groups.group",
                verbose_name="获奖社团",
            ),
        ),
    ]
