# Generated by Django 4.2.7 on 2025-07-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='level',
        ),
    ]
