# Generated by Django 4.2.7 on 2025-07-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_remove_award_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
        migrations.RemoveField(
            model_name='award',
            name='prize_description',
        ),
        migrations.RemoveField(
            model_name='award',
            name='prize_money',
        ),
        migrations.RemoveField(
            model_name='award',
            name='winner_count',
        ),
    ]
