# Generated by Django 4.2.7 on 2025-07-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competitions", "0001_initial"),
        ("videos", "0001_initial"),
        ("awards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardrecord",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_records",
                to="videos.video",
                verbose_name="获奖视频",
            ),
        ),
        migrations.AddField(
            model_name="award",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="competitions.competition",
                verbose_name="所属比赛",
            ),
        ),
    ]
