# Generated by Django 4.2.7 on 2025-08-10 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitionyear'),
        ('awards', '0003_remove_award_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardrecord',
            options={'ordering': ['-competition_year__year', '-created_at'], 'verbose_name': '获奖记录', 'verbose_name_plural': '获奖记录'},
        ),
        migrations.RemoveField(
            model_name='awardrecord',
            name='year',
        ),
        migrations.AddField(
            model_name='awardrecord',
            name='competition_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='award_records', to='competitions.competitionyear', verbose_name='比赛年份'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='awardrecord',
            index=models.Index(fields=['competition_year', 'award'], name='awards_awar_competi_d95023_idx'),
        ),
        migrations.AddIndex(
            model_name='awardrecord',
            index=models.Index(fields=['video', 'competition_year'], name='awards_awar_video_i_313801_idx'),
        ),
        migrations.AddIndex(
            model_name='awardrecord',
            index=models.Index(fields=['group', 'competition_year'], name='awards_awar_group_i_380a44_idx'),
        ),
    ]
