# Generated by Django 4.2.7 on 2025-07-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awardrecord",
            name="certificate_url",
        ),
        migrations.RemoveField(
            model_name="awardrecord",
            name="prize_received",
        ),
    ]
