# Generated by Django 4.2.7 on 2025-08-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_alter_awardrecord_options_remove_awardrecord_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awardrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '获奖记录', 'verbose_name_plural': '获奖记录'},
        ),
    ]
