# Generated by Django 4.2.7 on 2025-08-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0005_alter_awardrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardrecord',
            name='drama_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='剧名'),
        ),
    ]
