# Generated by Django 4.2.7 on 2025-07-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
