# Generated by Django 4.2.7 on 2026-01-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_videos_vide_group_i_0f5a19_idx_and_more'),
        ('groups', '0004_group_city_group_province_alter_group_location_and_more'),
        ('users', '0002_add_bio_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
        migrations.AddField(
            model_name='user',
            name='performed_videos',
            field=models.ManyToManyField(blank=True, related_name='performers', to='videos.video', verbose_name='参演视频'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_application_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申请时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_application_pending',
            field=models.BooleanField(default=False, verbose_name='是否有待审核的权限申请'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_application_reason',
            field=models.TextField(blank=True, verbose_name='申请理由'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='members', to='groups.group', verbose_name='所属社团'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('editor', '编辑'), ('viewer', '浏览用户'), ('contributor', '贡献者')], default='viewer', max_length=20, verbose_name='角色'),
        ),
    ]
