# Generated by Django 4.2.7 on 2025-07-09 08:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bv_number', models.CharField(max_length=20, unique=True, verbose_name='BV号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('url', models.URLField(verbose_name='视频链接')),
                ('thumbnail', models.URLField(blank=True, verbose_name='缩略图')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='时长')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='分辨率')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('view_count', models.IntegerField(default=0, verbose_name='播放量')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('performance_date', models.DateField(blank=True, null=True, verbose_name='表演时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('private', '私有'), ('deleted', '已删除')], default='published', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_original', models.BooleanField(default=True, verbose_name='是否原创')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('watch_duration', models.DurationField(blank=True, null=True, verbose_name='观看时长')),
                ('completion_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='完成率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='观看时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_views', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频观看记录',
                'verbose_name_plural': '视频观看记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('is_approved', models.BooleanField(default=True, verbose_name='是否审核通过')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='回复数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.videocomment', verbose_name='父评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频评论',
                'verbose_name_plural': '视频评论',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评分')),
                ('comment', models.TextField(blank=True, verbose_name='评价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频评分',
                'verbose_name_plural': '视频评分',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='VideoFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频收藏',
                'verbose_name_plural': '视频收藏',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['bv_number'], name='videos_vide_bv_numb_db759d_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status'], name='videos_vide_status_107761_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['is_featured'], name='videos_vide_is_feat_70e3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['performance_date'], name='videos_vide_perform_a22cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['upload_date'], name='videos_vide_upload__339bc0_idx'),
        ),
    ]
