# Generated by Django 4.2.7 on 2025-07-16 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_initial'),
        ('tags', '0001_initial'),
        ('competitions', '0003_competition_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bv_number', models.CharField(max_length=20, unique=True, verbose_name='BV号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('url', models.URLField(verbose_name='视频链接')),
                ('thumbnail', models.URLField(blank=True, verbose_name='缩略图')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='时长')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='分辨率')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('view_count', models.IntegerField(default=0, verbose_name='播放量')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('share_count', models.IntegerField(default=0, verbose_name='分享数')),
                ('upload_date', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('performance_date', models.DateField(blank=True, null=True, verbose_name='表演时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('private', '私有'), ('deleted', '已删除')], default='published', max_length=20, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_original', models.BooleanField(default=True, verbose_name='是否原创')),
                ('competition_year', models.IntegerField(blank=True, null=True, verbose_name='比赛年份')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='competitions.competition', verbose_name='所属比赛')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='groups.group', verbose_name='所属社团')),
                ('tags', models.ManyToManyField(related_name='videos', through='tags.VideoTag', to='tags.tag', verbose_name='标签')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bv_number'], name='videos_vide_bv_numb_db759d_idx'), models.Index(fields=['status'], name='videos_vide_status_107761_idx'), models.Index(fields=['is_featured'], name='videos_vide_is_feat_70e3c9_idx'), models.Index(fields=['performance_date'], name='videos_vide_perform_a22cd9_idx'), models.Index(fields=['upload_date'], name='videos_vide_upload__339bc0_idx'), models.Index(fields=['group'], name='videos_vide_group_i_535504_idx'), models.Index(fields=['competition'], name='videos_vide_competi_f15a44_idx'), models.Index(fields=['competition_year'], name='videos_vide_competi_d73454_idx')],
            },
        ),
    ]
