# Generated by Django 4.2.7 on 2025-07-16 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='videos_vide_status_107761_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videos_vide_is_feat_70e3c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videos_vide_perform_a22cd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videos_vide_upload__339bc0_idx',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_original',
        ),
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='performance_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='video',
            name='share_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='status',
        ),
        migrations.RemoveField(
            model_name='video',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='view_count',
        ),
    ]
