# Generated by Django 4.2.7 on 2025-07-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="groups.group",
                verbose_name="所属社团",
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(fields=["group"], name="videos_vide_group_i_535504_idx"),
        ),
    ]
