# Generated by Django 4.2.7 on 2025-07-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_videos_vide_status_107761_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='region',
            field=models.CharField(blank=True, max_length=50, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='年份'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['year'], name='videos_vide_year_babf4b_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['region'], name='videos_vide_region_48b9dc_idx'),
        ),
    ]
