# Generated by Django 4.2.7 on 2025-07-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0002_initial"),
        ("videos", "0002_video_group_video_videos_vide_group_i_535504_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="tags",
            field=models.ManyToManyField(
                related_name="videos",
                through="tags.VideoTag",
                to="tags.tag",
                verbose_name="标签",
            ),
        ),
    ]
