# Generated by Django 4.2.7 on 2025-08-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_region_video_year_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='video',
            name='videos_vide_competi_d73454_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videos_vide_region_48b9dc_idx',
        ),
        migrations.RemoveField(
            model_name='video',
            name='competition_year',
        ),
        migrations.RemoveField(
            model_name='video',
            name='region',
        ),
    ]
