# Generated by Django 4.2.7 on 2025-07-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0003_competition_year"),
        ("videos", "0003_video_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="competition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="videos",
                to="competitions.competition",
                verbose_name="所属比赛",
            ),
        ),
        migrations.AddField(
            model_name="video",
            name="competition_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="比赛年份"),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["competition"], name="videos_vide_competi_f15a44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="video",
            index=models.Index(
                fields=["competition_year"], name="videos_vide_competi_d73454_idx"
            ),
        ),
    ]
