# Generated by Django 4.2.7 on 2025-08-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_duplicate_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['group', 'year'], name='videos_vide_group_i_0f5a19_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['competition', 'year'], name='videos_vide_competi_20b5ed_idx'),
        ),
    ]
