# Generated by Django 4.2.7 on 2025-07-09 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='演出名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('type', models.CharField(choices=[('solo', '个人表演'), ('group', '团体表演'), ('stage_play', '舞台剧'), ('dance', '舞蹈'), ('music', '音乐'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('original_work', models.CharField(blank=True, max_length=255, verbose_name='原作品')),
                ('character_names', models.TextField(blank=True, verbose_name='角色名称')),
                ('debut_date', models.DateField(blank=True, null=True, verbose_name='首演时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='观看次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='groups.group', verbose_name='所属社团')),
            ],
            options={
                'verbose_name': '演出',
                'verbose_name_plural': '演出',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_videos', to='performances.performance', verbose_name='演出')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_videos', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '演出视频',
                'verbose_name_plural': '演出视频',
                'ordering': ['-created_at'],
                'unique_together': {('performance', 'video')},
            },
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['title'], name='performance_title_3863a8_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['type'], name='performance_type_a199a0_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['debut_date'], name='performance_debut_d_dc31c5_idx'),
        ),
    ]
