# Generated by Django 4.2.7 on 2026-04-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='socialaccountlink',
            new_name='authenticat_provide_dfc266_idx',
            old_name='authenticat_provide_3936f1_idx',
        ),
        migrations.RenameIndex(
            model_name='socialaccountlink',
            new_name='authenticat_user_id_c5a05a_idx',
            old_name='authenticat_user_id_a80627_idx',
        ),
    ]
