# Generated by Django 4.2.7 on 2025-07-09 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='比赛名称')),
                ('description', models.TextField(blank=True, verbose_name='比赛描述')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='举办地点')),
                ('website', models.URLField(blank=True, verbose_name='官方网站')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('organizer', models.CharField(blank=True, max_length=100, verbose_name='主办方')),
                ('sponsor', models.CharField(blank=True, max_length=100, verbose_name='赞助商')),
                ('participant_count', models.IntegerField(default=0, verbose_name='参赛人数')),
                ('award_count', models.IntegerField(default=0, verbose_name='奖项数量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'ordering': ['-year', '-start_date'],
                'indexes': [models.Index(fields=['name'], name='competition_name_57eea2_idx'), models.Index(fields=['year'], name='competition_year_fb6c6e_idx'), models.Index(fields=['start_date'], name='competition_start_d_21ef3b_idx')],
            },
        ),
    ]
