# Generated by Django 4.2.7 on 2025-07-16 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="比赛名称")),
                ("year", models.IntegerField(verbose_name="年份")),
                ("description", models.TextField(blank=True, verbose_name="比赛描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "比赛",
                "verbose_name_plural": "比赛",
                "ordering": ["-year"],
                "indexes": [
                    models.Index(fields=["name"], name="competition_name_57eea2_idx"),
                    models.Index(fields=["year"], name="competition_year_fb6c6e_idx"),
                ],
            },
        ),
    ]
