# Generated by Django 4.2.7 on 2025-07-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="competition",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "比赛",
                "verbose_name_plural": "比赛",
            },
        ),
        migrations.RemoveIndex(
            model_name="competition",
            name="competition_year_fb6c6e_idx",
        ),
        migrations.RemoveField(
            model_name="competition",
            name="year",
        ),
        migrations.AddField(
            model_name="competition",
            name="website",
            field=models.URLField(blank=True, verbose_name="官网链接"),
        ),
    ]
