# Generated by Django 4.2.7 on 2025-07-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0002_alter_competition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="year",
            field=models.IntegerField(default=2024, verbose_name="比赛年份"),
        ),
    ]
