# Generated by Django 4.2.7 on 2025-07-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competition_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='year',
        ),
    ]
