# Generated by Django 4.2.7 on 2025-08-10 03:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_remove_competition_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='年份')),
                ('description', models.TextField(blank=True, verbose_name='年份描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='competitions.competition', verbose_name='所属比赛')),
            ],
            options={
                'verbose_name': '比赛年份',
                'verbose_name_plural': '比赛年份',
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['competition', 'year'], name='competition_competi_f93175_idx'), models.Index(fields=['year'], name='competition_year_6d850d_idx')],
                'unique_together': {('competition', 'year')},
            },
        ),
    ]
