# Generated by Django 4.2.7 on 2025-08-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_competitionyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='award_display_order',
            field=models.JSONField(blank=True, default=list, verbose_name='奖项显示顺序'),
        ),
        migrations.AddField(
            model_name='competition',
            name='banner_gradient',
            field=models.JSONField(blank=True, default=list, verbose_name='Banner渐变色'),
        ),
        migrations.AddField(
            model_name='competition',
            name='banner_image',
            field=models.URLField(blank=True, verbose_name='Banner背景图片'),
        ),
    ]
