# Generated by Django 4.2.7 on 2025-10-10 03:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_competition_award_display_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='赛事日期')),
                ('title', models.CharField(max_length=200, verbose_name='赛事标题')),
                ('description', models.TextField(blank=True, verbose_name='赛事描述')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='联系方式')),
                ('website', models.URLField(blank=True, verbose_name='官网链接')),
                ('promotional_image', models.URLField(blank=True, verbose_name='宣传图链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='competitions.competition', verbose_name='关联比赛')),
            ],
            options={
                'verbose_name': '赛事信息',
                'verbose_name_plural': '赛事信息',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='competition_date_86ce11_idx'), models.Index(fields=['competition', 'date'], name='competition_competi_3d49be_idx')],
            },
        ),
    ]
