# Generated by Django 4.2.7 on 2026-03-12 12:04

from django.db import migrations, models


def copy_date_to_start_date(apps, schema_editor):
    """将旧的 date 字段值复制到 start_date"""
    Event = apps.get_model('competitions', 'Event')
    for event in Event.objects.all():
        if event.date and not event.start_date:
            event.start_date = event.date
            event.end_date = event.date  # 单日赛事，结束日期相同
            event.save()


def reverse_copy_date_to_start_date(apps, schema_editor):
    """回滚：将 start_date 复制回 date"""
    Event = apps.get_model('competitions', 'Event')
    for event in Event.objects.all():
        if event.start_date:
            event.date = event.start_date
            event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_event'),
    ]

    operations = [
        # 先添加新字段（允许为空）
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='赛事结束日期'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='赛事开始日期'),
        ),
        # 数据迁移：将 date 复制到 start_date
        migrations.RunPython(copy_date_to_start_date, reverse_copy_date_to_start_date),
        # 更新模型选项和索引
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': '赛事信息', 'verbose_name_plural': '赛事信息'},
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='competition_date_86ce11_idx',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='competition_competi_3d49be_idx',
        ),
        # 移除旧字段
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        # 添加新索引
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='competition_start_d_039550_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_date'], name='competition_end_dat_1b7893_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['competition', 'start_date'], name='competition_competi_982c4d_idx'),
        ),
    ]
