# Generated by Django 4.2.7 on 2026-04-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_videos_vide_group_i_0f5a19_idx_and_more'),
        ('competitions', '0008_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='赛区'),
        ),
        migrations.AddField(
            model_name='event',
            name='stage',
            field=models.CharField(blank=True, choices=[('preliminary', '初赛'), ('advancing', '复赛'), ('final', '决赛')], default='', max_length=20, verbose_name='赛事阶段'),
        ),
        migrations.AddField(
            model_name='event',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='events', to='videos.video', verbose_name='关联视频'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['region'], name='competition_region_1f5f4a_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['stage'], name='competition_stage_5ddd95_idx'),
        ),
    ]
