# Generated by Django 4.2.7 on 2025-07-09 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('category', models.CharField(choices=[('游戏IP', '游戏IP'), ('动漫IP', '动漫IP'), ('年份', '年份'), ('类型', '类型'), ('风格', '风格'), ('地区', '地区'), ('其他', '其他')], max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='颜色')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='tags.tag', verbose_name='标签')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '视频标签',
                'verbose_name_plural': '视频标签',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category'], name='tags_tag_categor_d20045_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active'], name='tags_tag_is_acti_9f235f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='videotag',
            unique_together={('video', 'tag')},
        ),
    ]
