# Generated by Django 4.2.7 on 2025-07-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='videos.video', verbose_name='视频'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tags_tag_name_3fbe74_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['category'], name='tags_tag_categor_d20045_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_active'], name='tags_tag_is_acti_9f235f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='videotag',
            unique_together={('video', 'tag')},
        ),
    ]
