# Generated by Django 4.2.7 on 2025-07-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('IP', 'IP'), ('年份', '年份'), ('风格', '风格'), ('地区', '地区'), ('其他', '其他')], max_length=20, verbose_name='分类'),
        ),
    ]
