# Generated by Django 4.2.7 on 2025-07-21 08:42

from django.db import migrations, models


def remove_style_tags(apps, schema_editor):
    """删除所有风格标签"""
    Tag = apps.get_model('tags', 'Tag')
    # 删除所有风格标签
    Tag.objects.filter(category='风格').delete()


def reverse_remove_style_tags(apps, schema_editor):
    """恢复风格标签（如果需要回滚）"""
    # 这里不恢复数据，因为删除的数据无法简单恢复
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_update_tag_categories'),
    ]

    operations = [
        # 先删除风格标签数据
        migrations.RunPython(remove_style_tags, reverse_remove_style_tags),
        # 然后修改字段选项
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('IP', 'IP'), ('年份', '年份'), ('地区', '地区'), ('其他', '其他')], max_length=20, verbose_name='分类'),
        ),
    ]
