# Generated by Django 4.2.7 on 2025-07-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_remove_style_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('IP', 'IP'), ('风格', '风格'), ('其他', '其他')], max_length=20, verbose_name='分类'),
        ),
    ]
