# Generated by Django 4.2.7 on 2026-05-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.html import strip_tags


def backfill_forum_stats(apps, schema_editor):
    ForumCategory = apps.get_model('forum', 'ForumCategory')
    Post = apps.get_model('forum', 'Post')
    Comment = apps.get_model('forum', 'Comment')

    for post in Post.objects.all().iterator():
        published_comments = Comment.objects.filter(post_id=post.id, is_active=True, status='published')
        last_comment = published_comments.order_by('-created_at').first()
        excerpt = ' '.join(strip_tags(post.content or '').split())[:300]
        post.excerpt = excerpt
        post.reply_count = published_comments.count()
        if last_comment:
            post.last_commented_at = last_comment.created_at
            post.last_commented_by_id = last_comment.author_id
        else:
            post.last_commented_at = post.created_at
        post.save(update_fields=['excerpt', 'reply_count', 'last_commented_at', 'last_commented_by'])

    for category in ForumCategory.objects.all().iterator():
        category.post_count = Post.objects.filter(category_id=category.id, is_active=True, status='published').count()
        category.comment_count = Comment.objects.filter(
            post__category_id=category.id,
            is_active=True,
            status='published',
        ).count()
        category.save(update_fields=['post_count', 'comment_count'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_forumattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', '帖子'), ('comment', '评论')], max_length=20)),
                ('reaction', models.CharField(default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾内容'), ('abuse', '攻击或骚扰'), ('copyright', '版权问题'), ('other', '其他')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('rejected', '已拒绝')], default='pending', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#d90614', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('pin', '置顶'), ('unpin', '取消置顶'), ('lock', '锁定'), ('unlock', '解锁'), ('feature', '设为精华'), ('unfeature', '取消精华'), ('hide', '隐藏'), ('restore', '恢复'), ('delete', '删除')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('content_json', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-last_commented_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_forum_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_forum_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_forum_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('published', '已发布'), ('hidden', '已隐藏'), ('deleted', '已删除')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='attached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='forum.post'),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('attached', '已关联'), ('orphaned', '孤儿文件'), ('blocked', '已屏蔽')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='forumattachment',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='allowed_roles',
            field=models.JSONField(blank=True, default=list, help_text='Empty means any authenticated user can post'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='post_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='content_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='last_commented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='last_commented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_commented_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('pending', '待审核'), ('hidden', '已隐藏'), ('deleted', '已删除')], default='published', max_length=20),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'status'], name='forum_comme_post_id_5bb6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='forum_comme_author__0ba0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'is_active'], name='forum_post_status_9c848e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status'], name='forum_post_categor_328197_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-is_pinned', '-last_commented_at'], name='forum_post_is_pinn_338b11_idx'),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_post_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postrevision',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='forum.post'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_moderation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='forum.post'),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_forum_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='forum.post'),
        ),
        migrations.AddField(
            model_name='forumreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='forum.post'),
        ),
        migrations.AddField(
            model_name='forumreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='forum.forumtag'),
        ),
        migrations.AddConstraint(
            model_name='forumreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('user', 'post', 'reaction'), name='unique_forum_post_reaction'),
        ),
        migrations.AddConstraint(
            model_name='forumreaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment', 'reaction'), name='unique_forum_comment_reaction'),
        ),
        migrations.RunPython(backfill_forum_stats, migrations.RunPython.noop),
    ]
