# Generated by Django 4.2.7 on 2025-07-16 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="社团名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="社团描述")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="group_logos/",
                        verbose_name="社团logo",
                    ),
                ),
                (
                    "founded_date",
                    models.DateField(blank=True, null=True, verbose_name="成立时间"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=100, verbose_name="所在地"),
                ),
                ("website", models.URLField(blank=True, verbose_name="官方网站")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="联系邮箱"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="联系电话"),
                ),
                ("weibo", models.URLField(blank=True, verbose_name="微博链接")),
                (
                    "wechat",
                    models.CharField(blank=True, max_length=50, verbose_name="微信号"),
                ),
                (
                    "qq_group",
                    models.CharField(blank=True, max_length=20, verbose_name="QQ群"),
                ),
                ("bilibili", models.URLField(blank=True, verbose_name="B站链接")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否活跃")),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否认证"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                ("video_count", models.IntegerField(default=0, verbose_name="视频数量")),
                ("award_count", models.IntegerField(default=0, verbose_name="获奖数量")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "社团",
                "verbose_name_plural": "社团",
                "ordering": ["-created_at"],
            },
        ),
    ]
