# Generated by Django 4.2.7 on 2025-07-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='社团名称')),
                ('description', models.TextField(blank=True, verbose_name='社团描述')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='group_logos/', verbose_name='社团logo')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='成立时间')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, verbose_name='官方网站')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('weibo', models.URLField(blank=True, verbose_name='微博链接')),
                ('wechat', models.CharField(blank=True, max_length=50, verbose_name='微信号')),
                ('qq_group', models.CharField(blank=True, max_length=20, verbose_name='QQ群')),
                ('bilibili', models.URLField(blank=True, verbose_name='B站链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('member_count', models.IntegerField(default=0, verbose_name='成员数量')),
                ('video_count', models.IntegerField(default=0, verbose_name='视频数量')),
                ('performance_count', models.IntegerField(default=0, verbose_name='演出数量')),
                ('award_count', models.IntegerField(default=0, verbose_name='获奖数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', '社长'), ('vice_leader', '副社长'), ('manager', '管理员'), ('member', '成员'), ('guest', '嘉宾')], default='member', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '不活跃'), ('pending', '待审核'), ('rejected', '已拒绝'), ('left', '已退出')], default='pending', max_length=20, verbose_name='状态')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='在社团中的昵称')),
                ('bio', models.TextField(blank=True, verbose_name='个人介绍')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='离开时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group', verbose_name='社团')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '社团成员',
                'verbose_name_plural': '社团成员',
                'ordering': ['-joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_videos', models.BooleanField(default=True, verbose_name='新视频通知')),
                ('notify_new_performances', models.BooleanField(default=True, verbose_name='新演出通知')),
                ('notify_awards', models.BooleanField(default=True, verbose_name='获奖通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='groups.group', verbose_name='社团')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_groups', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '社团关注',
                'verbose_name_plural': '社团关注',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='groups_grou_name_0806de_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_active'], name='groups_grou_is_acti_044fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_verified'], name='groups_grou_is_veri_96b2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_featured'], name='groups_grou_is_feat_cc5792_idx'),
        ),
    ]
