# Generated by Django 4.2.7 on 2025-07-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_is_veri_96b2f4_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='groups_grou_is_feat_cc5792_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_verified',
        ),
    ]
