# Generated by Django 4.2.7 on 2025-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_groups_grou_is_veri_96b2f4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='所在城市'),
        ),
        migrations.AddField(
            model_name='group',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='所在省份'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='详细地址'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['province'], name='groups_grou_provinc_409957_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['city'], name='groups_grou_city_1c8fe6_idx'),
        ),
    ]
