# Generated by Django 4.2.7 on 2026-02-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_city_group_province_alter_group_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='group_logos/', verbose_name='社团logo'),
        ),
    ]
